### ISSUE TITLE
FC - occupied should be correctly linked to fielding position

### ISSUE THREAD

**Issue by AloisSeckar** [AloisSeckar/WBSC-Scoring#152]
The number in **Ox** means the fielder, who decides to start playing to another runner. It should be enforced to be consistent with the out/decessive error play:

This is nonsense:
![image](https://github.com/AloisSeckar/WBSC-Scoring/assets/7399922/6d0d0904-4620-4e8c-a6bf-a07bcd02a968)

**Comment by lucafano04** [comment]
O1 is not possible in this case, it should be O6 so yes i suggest an automatism

**Comment by AloisSeckar** [comment]
Implemented in 97fdca79ba8bd977732e949d16cc14755ac4a462
