### ISSUE TITLE
FC - occupied is not a double-play situation if happedned due to bad throw

### ISSUE THREAD

**Issue by AloisSeckar** [AloisSeckar/WBSC-Scoring#203]
Follow-up to #171. If the double play was broken due to bad throw (so it is scored as FC -occupied), but then the subsequent out occurs during further base running, it is not considered a double-play (example 77 in Manual)

![image](https://github.com/AloisSeckar/WBSC-Scoring/assets/7399922/3c5d7eea-4130-45ec-917b-0a9198f1ec99)

However, currently it is not possible to differ this situation from "regular" FC - occupied, which would still allow to have a double play, if the running batter overruns first base.

Some new mechanism needs to be implemented - the easiest would probably be to have a new type of play in **GDP - safe** options.

**Comment by AloisSeckar** [comment]
Related to #180

**Comment by lucafano04** [comment]
> 17.4 DOUBLE PLAYS AND TRIPLE PLAYS
> 17.4.1 The Official Scorer shall credit participation in a double play or triple play to each fielder who makes an out or an assist when two or three players are put out, between the moment a pitch is thrown and the moment that the ball becomes dead or is again in the possession of the pitcher in his pitching position, unless an error or bad play occurs between the outs.

So the play on first is a O6 but the outs shall be connected but without a GDP

**Comment by AloisSeckar** [comment]
But there is an (extempted) error in this play - 2nd baseman made a bad throw to first, which is not accountable as an error itself during possible double play situation, but his wild throw allowed the runner to start advancing towards 2nd base, which he normally wouldn't. Because right fielder made a good back-up and a fast throw to 2nd base, the error is not recorded in the stats, but it broke the natural flow of the play. We cannot credit defence with DP when the sequence was break by a bad throw/catch.

Scoring manual reference:
![image](https://github.com/AloisSeckar/WBSC-Scoring/assets/7399922/5162e7f4-1cb8-4066-8c1f-63e1ff8318e4)

**Comment by AloisSeckar** [comment]
Implemented via #180
