### ISSUE TITLE
No SH with forced out

### ISSUE THREAD

**Issue by AloisSeckar** [AloisSeckar/WBSC-Scoring#219]
It is not possible to have a SH situation with a forced out. The valiation is not yet implemented.

**Comment by lucafano04** [comment]
Well it is possible if the runner is safe by an error in first base

**Comment by AloisSeckar** [comment]
> Well it is possible if the runner is safe by an error in first base

**Baseball rule 9.08 (c):** _Not score a sacrifice bunt when any runner is put out attempting to advance one base on a bunt, or would have been put out, except for a fielding errorr, in which case the Official Scorer shall charge the batter with a time at bat;_

Thats what I mean with "forced out". However, I see erros need to be taken into account as well.

**Comment by lucafano04** [comment]
Well if we want to take all the "Objective" part of the 2023-24 WBSC Official Rules Of Baseball:

> 16.5 THE SACRIFICES
> 16.5.1 SACRIFICE BUNT
> 16.5.1.1:
> The Official Scorer shall credit the batter with a sacrifice bunt when, with less than two outs, the batter advances one or more
runners with a bunt and is put out at first base, or would have been put out except for a fielding error. If in the judgment of the Official Scorer the batter hit the ball solely with the intention of getting a hit and not sacrificing his own chance of reaching first base for the purpose of advancing a runner or runners, he shall charge the batter one time At Bat.

From this you can see how a SH can be given to a batter even if it is safe, but if it is safe there should be a error witch can be any of Filding / Trowing / Muffed catch

**Comment by AloisSeckar** [comment]
SH + error for the batter is possible:
![image](https://github.com/AloisSeckar/WBSC-Scoring/assets/7399922/a3a4ca85-4a12-4a2d-9461-3f84615552dd)


The goal of this issue is to prevent following input from happening:

![image](https://github.com/AloisSeckar/WBSC-Scoring/assets/7399922/b3452599-6af6-4e32-aafa-f159f630db9a)

Currently there is only a validation that **at least one runner must advance**. There is no check implemented to prevent SH + forced out of one of the runners.

**Comment by lucafano04** [comment]
Well an advancment has been made, this shall be specified somewhere if the SH is the thid out

**Comment by AloisSeckar** [comment]
Although one runner advanced, the second one was out while trying to advance one base and thus this cannot be a sacrifice hit. It is written in the 16.5.1 rule, the last paragraph (it is practically the same as the MLB rule).

**Comment by lucafano04** [comment]
Right so a SH with a runner out shall not be aviable, in this case can a GDP be assigned? in the end it's a double play, the ball is grounded but shall (as an example) a GDP 34B written? in the end it's still a forced out and a but but with the spec of GDP in addition.
In an affermative case a new field and new immages shall be created 🙃

**Comment by lucafano04** [comment]
UPDATE: I just heard my supervisor, GDP 63B it is possible

**Comment by AloisSeckar** [comment]
GDP + bunt will be tracked in #222

**Comment by AloisSeckar** [comment]
validation implemented in 11c418ad0ea8933007c7152b7641e1fd04cf2e37
