### ISSUE TITLE
Score on same error (when decisive) should never be ER

### ISSUE THREAD

**Issue by lucafano04** [AloisSeckar/WBSC-Scoring#225]
This should not be possible:
![wbsc-scoring](https://github.com/AloisSeckar/WBSC-Scoring/assets/45771235/51b1f91a-9998-4e45-ad3a-7d02be0e736e)
corrected version:
![wbsc-scoring(1)](https://github.com/AloisSeckar/WBSC-Scoring/assets/45771235/ab579ff8-f0d7-419f-ae75-53df895f000e)

**Comment by AloisSeckar** [comment]
Well, that depends. If there were 2 outs prior to this play then you're right. But in general, illegal advances may turn into earned runs later as the inning develops. For example if batter 4 blasts a homerun, then it doesn't matter where the runner was. So I don't want to prevent it with rigid validation. 

The validation triggers if there is decessive error or K PB on given player, but not for extra base errors and illegal advances.

**Comment by lucafano04** [comment]
Right I missed that, sice this is a stand-alone this may be possible. It depends on the number of outs, the next plays and also the previus plays.
