### ISSUE TITLE
Double/triple, and extra base error are not working correctly

### ISSUE THREAD

**Issue by lucafano04** [AloisSeckar/WBSC-Scoring#226]
Error given:
![immagine](https://github.com/AloisSeckar/WBSC-Scoring/assets/45771235/d4e228f6-4451-4c03-a961-e6f2255527f4)
P.S. This is a hard coded message 🙃  did not foud corrisponding string inside the translation file.
Input and output:
![immagine](https://github.com/AloisSeckar/WBSC-Scoring/assets/45771235/faaaf7fd-cac2-477f-b524-f530c9ee1576)

no errors on the console...

**Comment by lucafano04** [comment]
String found:
hard coded at line n. 191 file `utils/wbsc-output.ts`

**Comment by AloisSeckar** [comment]
What a mess 🙈   Thanks for spotting, I am going to investigate

**Comment by AloisSeckar** [comment]
Should be fixed now. The solution is a little hacky, but all other 200 tests passed, so hopefully nothing got broken.

**Comment by AloisSeckar** [comment]
After refactoring #239 this fix should become obsolete
