### ISSUE TITLE
Immages loading on website

### ISSUE THREAD

**Issue by lucafano04** [AloisSeckar/WBSC-Scoring#228]
All images are not loaded correctly

![immagine](https://github.com/AloisSeckar/WBSC-Scoring/assets/45771235/cbb22deb-f525-4bb8-b8f9-eb3d6ecfe4bc)
![immagine](https://github.com/AloisSeckar/WBSC-Scoring/assets/45771235/5fb04da3-5909-464b-b52e-a09ce7858dfd)
![immagine](https://github.com/AloisSeckar/WBSC-Scoring/assets/45771235/23ad57e1-991e-4100-94fa-ecc4b3c080dd)

**Comment by AloisSeckar** [comment]
Yup, already found it - #227 

I will close this as duplicate, but thanks for the console screen, I will add it

**Comment by lucafano04** [comment]
> Yup, already found it - #227
> 
> I will close this as duplicate, but thanks for the console screen, I will add it

Just a few minutes before the first one, if I'd refreshed I would have seen it 😄
