### ISSUE TITLE
Update italian docs

### ISSUE THREAD

**Issue by AloisSeckar** [AloisSeckar/WBSC-Scoring#236]
In 2e1f1116a2297b9faf4f3cbdfa2341d7184381fb I made a few updates in `/help` page reflecting the latest changes ([see](https://github.com/AloisSeckar/WBSC-Scoring/commit/2e1f1116a2297b9faf4f3cbdfa2341d7184381fb#diff-50d68748119906b07c7fc63e67502f6e4a9550deceac37eed38aa2aa291a6a6e))

I don't feel competent to transfer those changes into Italian version.

@lucafano04 can you please have a look at it?

**Comment by lucafano04** [comment]
on it
